### ISSUE TITLE
untested, but init.livecd.patch should not be needed

### ISSUE THREAD

**Issue by NiKiZe** [numberly/gentoo-pxe-builder#5]
Nice work!
I have done some effort to try and get better official support for PXE booting of the minimal live cd.
When I happened to see this I might as well let you know of some updates in [#396467](https://bugs.gentoo.org/396467)

It should have made your `patch < ../files/init.livecd.patch` obsolete?

My work on the generic part is at [NiKiZe/Gentoo-iPXE](/NiKiZe/Gentoo-iPXE), it misses the sshd parts, will try and also look into better ways of only having to append data to cpio initrd instead of needing to repack squashfs to get these changes in.

Feel free to close this as won't fix, since this probably isn't a real issue for you.

**Comment by ultrabug** [comment]
Thanks @NiKiZe ; nice contribution there for a long waited topic

Do you think you could actually test it? I'd be happy to drop it from here afterwards

**Comment by ultrabug** [comment]
```bash
patching file init
Hunk #1 FAILED at 452.
Hunk #2 FAILED at 588
```

indeed the init changed quite a lot and the first elements of it are useless

**Comment by ultrabug** [comment]
Ok I tested and updated the build process + patch file to adjust to your comment, thanks mate!

**Comment by NiKiZe** [comment]
You where to quick to do it. ;)
But I can try to have another look anyway, or rather I will in connection to my other issue that is open.

I think you can completely remove the patch, at least I read the internals of `cache_cd_contents` to only execute if you have docache on the kernel cmdline ?
